using UnityEngine;
using UnityEngine.InputSystem;
using static UnityEngine.InputSystem.DefaultInputActions;

// Handles pausing the game, showing or hiding the pause UI,
// toggling the escape menu, and controlling cursor and music state.
public class GamePauseHandler : MonoBehaviour
{
    // Pause menu canvas shown when the game is paused.
    [SerializeField] private GameObject pauseCanvas;
    // Escape menu that can be toggled separately.
    [SerializeField] private GameObject escapeMenu;
    // Background music source that is paused and resumed with the game.
    [SerializeField] private AudioSource backgroundMusic;

    // Input actions generated by the Input System.
    private Player input;
    // Tracks whether the game is currently paused.
    private bool gameIsFrozen;

    private void Awake()
    {
        // Create a new input action instance.
        input = new Player();
    }

    private void OnEnable()
    {
        // Enable player actions and subscribe to pause and escape inputs.
        input.PlayerActions.Enable();
        input.PlayerActions.Pause.performed += OnPause;
        input.PlayerActions.Escape.performed += OnEscape;
    }

    private void OnDisable()
    {
        // Unsubscribe from input callbacks and disable the action map.
        input.PlayerActions.Pause.performed -= OnPause;
        input.PlayerActions.Escape.performed -= OnEscape;
        input.PlayerActions.Disable();
    }

    private void Start()
    {
        // Make sure all menus are hidden when the scene starts.
        if (pauseCanvas != null)
            pauseCanvas.SetActive(false);

        if (escapeMenu != null)
            escapeMenu.SetActive(false);

        // Start the game in an unpaused state with the cursor locked and hidden.
        Time.timeScale = 1f;
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
        gameIsFrozen = false;
    }

    private void OnPause(InputAction.CallbackContext ctx)
    {
        // Toggle the pause state when the pause action is performed.
        TogglePauseState();
    }

    private void OnEscape(InputAction.CallbackContext ctx)
    {
        // Toggle the escape menu when the escape action is performed.
        ToggleEscapeMenu();
    }

    private void TogglePauseState()
    {
        // Switch between paused and unpaused states.
        if (gameIsFrozen)
            HidePauseMenu();
        else
            ShowPauseMenu();
    }

    private void ShowPauseMenu()
    {
        // Show the pause menu if it exists.
        if (pauseCanvas != null)
            pauseCanvas.SetActive(true);

        // Hide the escape menu while the pause menu is open.
        if (escapeMenu != null)
            escapeMenu.SetActive(false);

        // Pause the background music if it is currently playing.
        if (backgroundMusic != null && backgroundMusic.isPlaying)
            backgroundMusic.Pause();

        // Freeze game time and unlock the cursor for UI interaction.
        Time.timeScale = 0f;
        Cursor.visible = true;
        Cursor.lockState = CursorLockMode.None;
        gameIsFrozen = true;
    }

    private void HidePauseMenu()
    {
        // Hide the pause menu if it exists.
        if (pauseCanvas != null)
            pauseCanvas.SetActive(false);

        // Also hide the escape menu when resuming the game.
        if (escapeMenu != null)
            escapeMenu.SetActive(false);

        // Resume background music if an audio source is assigned.
        if (backgroundMusic != null)
            backgroundMusic.UnPause();

        // Resume game time and restore the locked gameplay cursor state.
        Time.timeScale = 1f;
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
        gameIsFrozen = false;
    }

    public void ContinueButton()
    {
        // UI button callback used to resume the game.
        HidePauseMenu();
    }

    public void ToggleEscapeMenu()
    {
        // Stop if no escape menu object was assigned.
        if (escapeMenu == null) return;

        // Toggle the current visibility state of the escape menu.
        bool isActive = escapeMenu.activeSelf;
        escapeMenu.SetActive(!isActive);
    }
}